name: Run Grading

on:
  workflow_dispatch:

jobs:
  grading:
    runs-on: ubuntu-latest
    name: grading
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python  
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install canvasapi
          python -m pip install PyGithub
          python -m pip install web3

      - name: Run Python script
        env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_REPO: ${{ secrets.GIT_REPO }}
          CANVAS_USER: ${{ secrets.CANVAS_USER }}
          CANVAS_COURSE_ID: ${{ secrets.CANVAS_COURSE_ID }}
          CHAINSTACK_NODE: ${{ secrets.CHAINSTACK_NODE }}
          OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
          OWNER_PRIVATE_KEY: ${{ secrets.OWNER_PRIVATE_KEY }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          STUDENT_ADDRESS: ${{ secrets.STUDENT_ADDRESS }}
        run: |
          python .github/workflows/grading.py
